// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Greet: typeof import('./components/Greet.vue')['default']
    IconCarbonCertificate: typeof import('~icons/carbon/certificate')['default']
    IconCarbonServerDns: typeof import('~icons/carbon/server-dns')['default']
    IconCibDocker: typeof import('~icons/cib/docker')['default']
    IconEpSetting: typeof import('~icons/ep/setting')['default']
    IconEpSettingOutline: typeof import('~icons/ep/setting-outline')['default']
    'IconIc:outlineKeyboardArrowLeft': typeof import('~icons/ic/outline-keyboard-arrow-left')['default']
    'IconIc:outlineKeyboardArrowRight': typeof import('~icons/ic/outline-keyboard-arrow-right')['default']
    IconIcBaselineContentCopy: typeof import('~icons/ic/baseline-content-copy')['default']
    IconIcOutlineArrowLeft: typeof import('~icons/ic/outline-arrow-left')['default']
    IconIcOutlineArrowRight: typeof import('~icons/ic/outline-arrow-right')['default']
    IconIcOutlineKeyboardArrowLeft: typeof import('~icons/ic/outline-keyboard-arrow-left')['default']
    IconIcOutlineKeyboardArrowRight: typeof import('~icons/ic/outline-keyboard-arrow-right')['default']
    IconIcRoundArrowBackIos: typeof import('~icons/ic/round-arrow-back-ios')['default']
    IconIcRoundArrowFollowIos: typeof import('~icons/ic/round-arrow-follow-ios')['default']
    IconIcRoundArrowLeft: typeof import('~icons/ic/round-arrow-left')['default']
    IconIonFileTrayFullSharp: typeof import('~icons/ion/file-tray-full-sharp')['default']
    IconIonMdAppstore: typeof import('~icons/ion/md-appstore')['default']
    IconIonMdFile: typeof import('~icons/ion/md-file')['default']
    IconIonSetting: typeof import('~icons/ion/setting')['default']
    IconIonSettings: typeof import('~icons/ion/settings')['default']
    IconMdiArrow: typeof import('~icons/mdi/arrow')['default']
    IconMdiCertificate: typeof import('~icons/mdi/certificate')['default']
    IconMdiCloudArrowRight: typeof import('~icons/mdi/cloud-arrow-right')['default']
    IconMdiCopy: typeof import('~icons/mdi/copy')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
