// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Greet: typeof import('./components/Greet.vue')['default']
    IconCarbonCertificate: typeof import('~icons/carbon/certificate')['default']
    IconCarbonServerDns: typeof import('~icons/carbon/server-dns')['default']
    IconCibDocker: typeof import('~icons/cib/docker')['default']
    'IconIc:outlineKeyboardArrowLeft': typeof import('~icons/ic/outline-keyboard-arrow-left')['default']
    IconIcBaselineContentCopy: typeof import('~icons/ic/baseline-content-copy')['default']
    IconIcOutlineKeyboardArrowRight: typeof import('~icons/ic/outline-keyboard-arrow-right')['default']
    IconIonFileTrayFullSharp: typeof import('~icons/ion/file-tray-full-sharp')['default']
    IconIonMdAppstore: typeof import('~icons/ion/md-appstore')['default']
    IconIonSettings: typeof import('~icons/ion/settings')['default']
    IconMdiCertificate: typeof import('~icons/mdi/certificate')['default']
    IconRiPassExpiredLine: typeof import('~icons/ri/pass-expired-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
