// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Greet: typeof import('./components/Greet.vue')['default']
    IconCibDocker: typeof import('~icons/cib/docker')['default']
    IconEpSetting: typeof import('~icons/ep/setting')['default']
    IconEpSettingOutline: typeof import('~icons/ep/setting-outline')['default']
    IconIonFileTrayFullSharp: typeof import('~icons/ion/file-tray-full-sharp')['default']
    IconIonMdAppstore: typeof import('~icons/ion/md-appstore')['default']
    IconIonMdFile: typeof import('~icons/ion/md-file')['default']
    IconIonSetting: typeof import('~icons/ion/setting')['default']
    IconIonSettings: typeof import('~icons/ion/settings')['default']
    IconMdiCertificate: typeof import('~icons/mdi/certificate')['default']
    IconMdiCloudArrowRight: typeof import('~icons/mdi/cloud-arrow-right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
